### PR TITLE
Fix flaky tests and fix #69

### LINKED ISSUE #69: Client connection can be closed before proxy returns protocol error
When a protocol error happens (as part of protocol version negotiation or not), the proxy invokes the shutdown mechanism for that connection after sending the response to the write queue but due to #68 the client may see the connection closed without the protocol error actually being sent.

Due to this, the proxy should at least not shutdown the connection when a protocol error happens while #68 is not addressed.

### PR DESCRIPTION
**Pull request by joao-r-reis**
Fix #69 
Fix more flaky tests

### CODE REVIEW

File: integration-tests/tls_test.go [hunk 1]
```diff
@@ -1056,16 +1057,36 @@ func testProxyClientTls(t *testing.T, ccmSetup *setup.CcmTestSetup,
 
 	logMessages := buffer.String()
 
+	warnCheckFail := false
+	warnCheckDone := false
```
Comment (grighetto) [inline integration-tests/tls_test.go:1061]: The `Done` suffix here confused me for a second, I thought it would be set when the result of some async processing was done, but in reality this value is simply set when a warning is expected. My suggestion would be to name this `warningExpected` instead. The same goes for `errCheckDone` below, `errExpected`.

File: integration-tests/tls_test.go [hunk 2]
```diff
@@ -1056,16 +1057,36 @@ func testProxyClientTls(t *testing.T, ccmSetup *setup.CcmTestSetup,
...
 		if proxyTlsConfig.errMsgExpected != "" {
-			require.True(t, strings.Contains(err.Error(), proxyTlsConfig.errMsgExpected), err.Error())
+			errCheckDone = true
+			if !strings.Contains(err.Error(), proxyTlsConfig.errMsgExpected) {
+				errCheckFail = true
+				t.Logf("%v not found in %v", err.Error(), proxyTlsConfig.errMsgExpected)
+			}
+		}
+		if errCheckDone && warnCheckDone {
+			require.True(t, !errCheckFail || !warnCheckFail) // only 1 check needs to pass in this scenario
```
Comment (grighetto) [inline integration-tests/tls_test.go:1082]: Nit: I think this would be clearer given the other requires are False too:

`require.False(t, errCheckFail && warnCheckFail)`

File: integration-tests/tls_test.go [hunk 3]
```diff
@@ -1340,6 +1361,14 @@ func getClientSideVerifyConnectionCallback(rootCAs *x509.CertPool) func(cs tls.C
 			}
 		}
 		_, err := cs.PeerCertificates[0].Verify(opts)
+		if err != nil {
+			// use zerolog to avoid interacting with proxy's log messages that are used for assertions in the test
```
Comment (grighetto) [inline integration-tests/tls_test.go:1365]: Just for my understanding, are we suppressing the log messages from a lib to avoid throwing our log assertions off?

Comment (joao-r-reis) [reply integration-tests/tls_test.go:1365]: The goal is to avoid throwing our log assertions off but we aren't suppressing any log messages. We are capturing the log output from the `logrus` library which is what the proxy uses and the test client uses `zerolog`. To avoid messing with the log assertions I decided to use `zerolog` here on this test code in particular instead of `logrus`

File: integration-tests/tls_test.go (hunk 2 above)
Comment (joao-r-reis) [reply integration-tests/tls_test.go:1082]: I actually set this to `require.True` because to me it felt easier to understand but since I added a comment anyway I can use `require.False` to be consistent with the others

File: proxy/pkg/zdmproxy/clientconn.go [hunk 4]
```diff
@@ -174,14 +175,15 @@ func (cc *ClientConnector) listenForRequests() {
...
 			} else if protocolErrResponseFrame != nil {
-				f = protocolErrResponseFrame
-				if !protocolErrOccurred {
-					protocolErrOccurred = true
-					cc.sendResponseToClient(protocolErrResponseFrame)
-					cc.clientHandlerShutdownRequestCancelFn()
-					setDrainModeNowFunc()
-					continue
-				}
+				alreadySentProtocolErr = protocolErrResponseFrame
```
Comment (alicel) [inline proxy/pkg/zdmproxy/clientconn.go:178]: should this assignment happen after `cc.sendResponseToClient(protocolErrResponseFrame)`?

File: proxy/pkg/zdmproxy/clientconn.go [hunk 5]
```diff
@@ -174,14 +175,15 @@ func (cc *ClientConnector) listenForRequests() {
...
+				protocolErrOccurred = true
+				cc.sendResponseToClient(protocolErrResponseFrame)
+				continue
+			} else if alreadySentProtocolErr != nil {
```
Comment (alicel) [inline proxy/pkg/zdmproxy/clientconn.go:182]: Just to check that I understand correctly. The intended behaviour with this change is: if a protocol error is sent on the connection, then we want to ensure that all other potentially pending responses that may still be returned are replaced by that protocol error (unless they were themselves protocol errors in the first place). So we're keeping the already returned protocol error to replace the frame of any subsequent non-protocol error response with it.

The idea is to ensure that we do not send seemingly valid responses on a connection on which a protocol error was returned while this connection is being drained. 

Is this correct?

File: integration-tests/tls_test.go (hunk 2 above)
Comment (joao-r-reis) [reply integration-tests/tls_test.go]: done

File: integration-tests/tls_test.go (hunk 1 above)
Comment (joao-r-reis) [reply integration-tests/tls_test.go]: done

File: proxy/pkg/zdmproxy/clientconn.go [hunk 6]
```diff
@@ -174,14 +175,15 @@ func (cc *ClientConnector) listenForRequests() {
 					err, cc.clientHandlerContext, cc.clientHandlerCancelFunc, ClientConnectorLogPrefix, "reading", connectionAddr)
 				break
 			} else if protocolErrResponseFrame != nil {
-				f = protocolErrResponseFrame
-				if !protocolErrOccurred {
-					protocolErrOccurred = true
-					cc.sendResponseToClient(protocolErrResponseFrame)
-					cc.clientHandlerShutdownRequestCancelFn()
```
Comment (grighetto) [inline proxy/pkg/zdmproxy/clientconn.go:181]: It looks like `clientHandlerShutdownRequestCancelFn` is not called anywhere anymore, we should probably remove it from the struct.

**Review by alicel — APPROVED** [review]
Looks fine to me. I left a question and a tentative suggestion but nothing that would prevent it from being approved.

File: proxy/pkg/zdmproxy/clientconn.go (hunk 5 above)
Comment (joao-r-reis) [reply proxy/pkg/zdmproxy/clientconn.go:182]: Yes, but also the main change is that we no longer trigger the connection shutdown mechanism so the connection will be left in an unusable state (constant protocol errors) but it will be up to the driver to close it (at least until we address #68 )

File: proxy/pkg/zdmproxy/clientconn.go (hunk 4 above)
Comment (joao-r-reis) [reply proxy/pkg/zdmproxy/clientconn.go:178]: Doesn't really matter because there is no concurrency here, it's a single goroutine with a `for` loop

File: proxy/pkg/zdmproxy/clientconn.go (hunk 6 above)
Comment (joao-r-reis) [reply proxy/pkg/zdmproxy/clientconn.go:181]: We want to call it once #68 is addressed, maybe I can add a comment about this

Comment (joao-r-reis) [reply proxy/pkg/zdmproxy/clientconn.go:181]: done

**Review by grighetto — APPROVED** [review]
👍
